//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathChatBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageLog
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int MessageId { get; set; }
        public int ResponseOnMessageId { get; set; }
        public System.DateTime SendDate { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual Message Message1 { get; set; }
        public virtual User User { get; set; }
    }
}
