//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathChatBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpRequest
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<int> MaterialExampleId { get; set; }
        public Nullable<int> AssignmentId { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual MaterialExample MaterialExample { get; set; }
        public virtual User User { get; set; }
        public virtual Assignment Assignment { get; set; }
    }
}
