//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathChatBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialExamples = new HashSet<MaterialExample>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> TopicId { get; set; }
        public string Source { get; set; }
        public int ShowOrderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialExample> MaterialExamples { get; set; }
        public virtual Term Term { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
