//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathChatBot.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MathChatBotEntities : DbContext
    {
        public MathChatBotEntities()
            : base("name=MathChatBotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserClassRelation> UserClassRelations { get; set; }
        public virtual DbSet<UserRoleRelation> UserRoleRelations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<MaterialExample> MaterialExamples { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<HelpRequest> HelpRequests { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
    }
}
