//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathChatBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int MessageTypeId { get; set; }
        public System.DateTime SendDate { get; set; }
        public string Text { get; set; }
    
        public virtual MessageType MessageType { get; set; }
        public virtual User User { get; set; }
    }
}
