//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathChatBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathChatBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acos can only contain numbers between -1 and 1..
        /// </summary>
        public static string acos_can_only_contain_numbers_between_minus1_and_1 {
            get {
                return ResourceManager.GetString("acos_can_only_contain_numbers_between_minus1_and_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        public static string activated {
            get {
                return ResourceManager.GetString("activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add users from file.
        /// </summary>
        public static string add_users_from_file {
            get {
                return ResourceManager.GetString("add_users_from_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Add Users to Class.
        /// </summary>
        public static string add_users_to_class {
            get {
                return ResourceManager.GetString("add_users_to_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding users from file. Please wait....
        /// </summary>
        public static string adding_users_from_file_please_wait {
            get {
                return ResourceManager.GetString("adding_users_from_file_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin controls.
        /// </summary>
        public static string admin_controls {
            get {
                return ResourceManager.GetString("admin_controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Controls.
        /// </summary>
        public static string admin_controls_title {
            get {
                return ResourceManager.GetString("admin_controls_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All topics.
        /// </summary>
        public static string all_topics {
            get {
                return ResourceManager.GetString("all_topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any news.
        /// </summary>
        public static string any_news {
            get {
                return ResourceManager.GetString("any_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two students were arrested this morning for trying to smuggle 20 GB of memes into Sweden. Both students are claiming they were only for “personal use”..
        /// </summary>
        public static string any_news_response {
            get {
                return ResourceManager.GetString("any_news_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - MathChatBot.
        /// </summary>
        public static string application_title {
            get {
                return ResourceManager.GetString("application_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asin can only contain numbers between -1 and 1..
        /// </summary>
        public static string asin_can_only_contain_numbers_between_minus1_and_1 {
            get {
                return ResourceManager.GetString("asin_can_only_contain_numbers_between_minus1_and_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment no..
        /// </summary>
        public static string assignment_no {
            get {
                return ResourceManager.GetString("assignment_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string assignments {
            get {
                return ResourceManager.GetString("assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class name.
        /// </summary>
        public static string class_name {
            get {
                return ResourceManager.GetString("class_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Class Overview.
        /// </summary>
        public static string class_overview {
            get {
                return ResourceManager.GetString("class_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string classes {
            get {
                return ResourceManager.GetString("classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear result.
        /// </summary>
        public static string clear_result {
            get {
                return ResourceManager.GetString("clear_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert material.
        /// </summary>
        public static string convert_material {
            get {
                return ResourceManager.GetString("convert_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add class.
        /// </summary>
        public static string could_not_add_class {
            get {
                return ResourceManager.GetString("could_not_add_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the term.
        /// </summary>
        public static string could_not_add_the_term {
            get {
                return ResourceManager.GetString("could_not_add_the_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the topic.
        /// </summary>
        public static string could_not_add_the_topic {
            get {
                return ResourceManager.GetString("could_not_add_the_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not make a help request..
        /// </summary>
        public static string could_not_make_a_help_request {
            get {
                return ResourceManager.GetString("could_not_make_a_help_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot not remove the definition. It still has some associations to other tables in the database..
        /// </summary>
        public static string could_not_remove_definition {
            get {
                return ResourceManager.GetString("could_not_remove_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot not remove the term. It still has some associations to other tables in the database..
        /// </summary>
        public static string could_not_remove_the_term {
            get {
                return ResourceManager.GetString("could_not_remove_the_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot not remove the topic. It still has some associations to other tables in the database..
        /// </summary>
        public static string could_not_remove_the_topic {
            get {
                return ResourceManager.GetString("could_not_remove_the_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the following problems has occured:
        ///
        ///1. You have given a name that is not at least 2 letters long.
        ///2. You have given a password that is not at least 8 characters long..
        /// </summary>
        public static string create_user_error {
            get {
                return ResourceManager.GetString("create_user_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string current {
            get {
                return ResourceManager.GetString("current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,AssignmentNo,TermId,Source,AnswerA,AnswerB,AnswerC,AnswerD,AnswerE,AnswerF,AnswerG
        ///1,1,23,&quot;iVBORw0KGgoAAAANSUhEUgAAAYAAAAGtCAYAAAAf9aNXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAEkMSURBVHhe7d0HWBTX+gZwEUGxosaKvRCNJZa/xp4Yo9FoVOwlKoq9xBYTE5WosRuNvUaN3diN9arR2DUae71qLNd+FYhAgAub97/fMAsLDrDALrA77+955lGHBZfZmfPOnPnmnHQgIiJdYgAQEekUA4CISKfeDICQu9g50Qefvl8Nld+tiArv1sAnPpPxy51A3P+5D1qNPYkw9aXC4HcZW2ZOxNw9txCoriMiorQvZgD4HcLX/+eOvB+Mxu4/g2GQdWEvcH79aDStUAh5M2dAkb4HEKq8WITiYP+icE6XDk6uV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dbo_Assignments {
            get {
                return ResourceManager.GetString("dbo_Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Name
        ///3,&quot;B100&quot;
        ///4,&quot;B200&quot;
        ///5,&quot;B300&quot;
        ///6,&quot;B400&quot;
        ///7,&quot;B500&quot;
        ///.
        /// </summary>
        public static string dbo_Classes {
            get {
                return ResourceManager.GetString("dbo_Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,UserId,MaterialId,MaterialExampleId,AssignmentId,TermId
        ///95,23,32,,,23
        ///96,23,,3,,23
        ///.
        /// </summary>
        public static string dbo_HelpRequests {
            get {
                return ResourceManager.GetString("dbo_HelpRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,MaterialId,Source,ShowOrderId
        ///1,25,&quot;iVBORw0KGgoAAAANSUhEUgAAAYcAAALsCAYAAAAIxXt6AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7J0HXFTH+vejERCxoMaCaMRGbBgRew0SFYNtsXeEGHskNlBwBQ3YEcSGRrGhxoYN9dpF0SR6NQiKXjsXVLxSrsAF/rv7/t4zZwvbWRRwweebz/lEzjl7yjPPzG+emTkzX4AgCIIg1CBxIAiCIDTQFIecpzgZ4IGBvTrA/ts2sPu2M37wWI4TTzLx4vcpcPW7gTzZqQxJ2j0cCQpA6OlHyJTtK1okSLt3BEEBoTj9SH4HMV7u/xk/OPVCt04OaOswE8dzZIdKFAleX1gPH29veBdi893xF7JlV9CPtnc3HsQv9+PnH5zQq1snOLR1wMwSTwQR7u9ZgJ9+/BE/GrT9hPm74rhf [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dbo_MaterialExamples {
            get {
                return ResourceManager.GetString("dbo_MaterialExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,TermId,TopicId,Source,ShowOrderId
        ///1,1,,&quot;iVBORw0KGgoAAAANSUhEUgAAAYYAAAF1CAYAAADshk1SAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAMAySURBVHhe7L0HVFTHG//9MxEQsWCMSZSoWEJsGBVbYguaWGLFXmMhxh5NbCiIWABRFBAsmIglYm9RUY+9YYoejYrttSEHEPhLeSkv8N+95/PeLbDFZVkUE5PM5xzO0Xt378w888zznZl79z7/QyAQCAQCPUwLQ/ZDjq+Zj3vvDrRp24HPXT+nfdvP6DpsBst2XeO5Uvu5vxvpGftm9eIL1w582tqFlpP2kqE99fcgkX7rACHL1nHiYbb2WOmguBPJ/MkTmTjRsr/J87ZxW6H98j8QKf0WB0KWse7EQ0rXkgKBoDiMhEEi6bQP3WqVw9qhC/N23eB5QXDJfsKplUNpWMGKd1wmsO1u [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dbo_Materials {
            get {
                return ResourceManager.GetString("dbo_Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Name
        ///1,&quot;Administrator&quot;
        ///4,&quot;Student&quot;
        ///3,&quot;Teacher&quot;
        ///.
        /// </summary>
        public static string dbo_Roles {
            get {
                return ResourceManager.GetString("dbo_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,TopicId,Name
        ///1,1,&quot;Quadratic equation&quot;
        ///3,1,&quot;Discriminant&quot;
        ///4,3,&quot;Triangle&quot;
        ///6,3,&quot;Parallelogram&quot;
        ///7,3,&quot;Trapezoid&quot;
        ///8,3,&quot;Circle&quot;
        ///9,3,&quot;Cylinder&quot;
        ///10,3,&quot;Rectangular Prism&quot;
        ///11,3,&quot;Sphere&quot;
        ///12,3,&quot;Cone&quot;
        ///13,3,&quot;Pyramid&quot;
        ///14,6,&quot;Acute triangle&quot;
        ///15,6,&quot;Obtuse triangle&quot;
        ///16,6,&quot;Similar triangles&quot;
        ///17,6,&quot;Isosceles triangle&quot;
        ///18,6,&quot;Equilateral triangle&quot;
        ///19,6,&quot;Pythagoras&quot;
        ///20,6,&quot;Hypotenuse&quot;
        ///21,6,&quot;Cathetus&quot;
        ///22,6,&quot;Unit circle&quot;
        ///23,6,&quot;Sine&quot;
        ///24,6,&quot;Cosine&quot;
        ///25,6,&quot;Tangent&quot;
        ///26,4,&quot;Numbers&quot;
        ///27,4,&quot;Order of Operations&quot;
        ///28, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dbo_Terms {
            get {
                return ResourceManager.GetString("dbo_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Name
        ///1,&quot;Equations&quot;
        ///2,&quot;Functions&quot;
        ///3,&quot;Geometry&quot;
        ///4,&quot;Numbers and Arithmetic&quot;
        ///5,&quot;Probability&quot;
        ///6,&quot;Trigonometry&quot;
        ///.
        /// </summary>
        public static string dbo_Topics {
            get {
                return ResourceManager.GetString("dbo_Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,UserId,ClassId
        ///1,4,3
        ///2,5,3
        ///3,6,3
        ///4,7,3
        ///5,8,3
        ///6,9,3
        ///7,10,3
        ///8,11,3
        ///9,12,3
        ///10,13,3
        ///11,14,3
        ///12,15,3
        ///13,16,3
        ///14,17,3
        ///15,18,3
        ///16,19,3
        ///17,20,3
        ///18,21,3
        ///19,22,3
        ///20,23,3
        ///21,24,3
        ///110,25,3
        ///23,26,3
        ///24,27,3
        ///25,28,3
        ///26,29,3
        ///27,30,3
        ///28,31,3
        ///29,32,3
        ///30,33,4
        ///31,34,4
        ///111,35,3
        ///33,36,4
        ///34,37,4
        ///35,38,4
        ///36,39,4
        ///37,40,4
        ///38,41,4
        ///39,42,4
        ///40,43,4
        ///41,44,4
        ///42,45,4
        ///43,46,4
        ///44,47,4
        ///45,48,4
        ///46,49,4
        ///47,50,4
        ///48,51,4
        ///49,52,4
        ///50,53,4
        ///51,54,4
        ///52,55,4
        ///53,56,4
        ///54,57,4
        ///55,58,4
        ///56,59,4
        ///57 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dbo_UserClassRelations {
            get {
                return ResourceManager.GetString("dbo_UserClassRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,UserId,RoleId
        ///1,1,1
        ///9,4,4
        ///10,5,4
        ///11,6,4
        ///12,7,4
        ///13,8,4
        ///14,9,4
        ///15,10,4
        ///16,11,4
        ///17,12,4
        ///18,13,4
        ///19,14,4
        ///20,15,4
        ///21,16,4
        ///22,17,4
        ///23,18,4
        ///24,19,4
        ///25,20,4
        ///26,21,4
        ///27,22,4
        ///28,23,4
        ///29,24,4
        ///30,25,4
        ///31,26,4
        ///32,27,4
        ///33,28,4
        ///34,29,4
        ///35,30,4
        ///36,31,4
        ///37,32,4
        ///38,33,4
        ///39,34,4
        ///40,35,4
        ///41,36,4
        ///42,37,4
        ///43,38,4
        ///44,39,4
        ///45,40,4
        ///46,41,4
        ///47,42,4
        ///48,43,4
        ///49,44,4
        ///50,45,4
        ///51,46,4
        ///52,47,4
        ///53,48,4
        ///54,49,4
        ///55,50,4
        ///56,51,4
        ///57,52,4
        ///58,53,4
        ///59,54,4
        ///60,55,4
        ///61,56,4
        ///62,57,4
        ///63,58,4        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dbo_UserRoleRelations {
            get {
                return ResourceManager.GetString("dbo_UserRoleRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Password,FirstName,LastName,Username,IsActivated
        ///1,&quot;0wGoCAILO1yebGPmgc9F6rnwuKhmS0KuFbRGQaTeRVxSaUT2vKNeORlRdvdDtdvcSjZKXwa0HEbqRSLA7c12s+OfiZZFYLHlA7xhQyDuZa6QQJkp9daYXuYb5CRSjfeB&quot;,&quot;Jakob&quot;,&quot;Precht&quot;,&quot;japr&quot;,True
        ///4,&quot;VisP8NRR7ASQ0Mdqv+KF7eQomOjrpx8sgkVHQ+NvsKvPfEd3BCl9cpRT7VljMPh5+wEx3Cm6vOwVaw/9AMvBikGeRTKWHoDVEnRcGsvgys+DJAHX4Gsyhwpr2azBxtIk&quot;,&quot;Hamish&quot;,&quot;Newman&quot;,&quot;hane1&quot;,True
        ///5,&quot;smPbx1NlLyYK/DcJd3vczisfi3aRqWpb+/LwYALBlIo5epY9B3MPdwpbZXXSY7xTJNRS4VxvCyWsbQ/BqI0kDx0GcuIGIlwnEtPP0k8S9n98eabkU0mmKEXq7mYgpqRG [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dbo_Users {
            get {
                return ResourceManager.GetString("dbo_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        public static string definitions {
            get {
                return ResourceManager.GetString("definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Definitions and Assignments.
        /// </summary>
        public static string defitions_and_assignments {
            get {
                return ResourceManager.GetString("defitions_and_assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not help?.
        /// </summary>
        public static string did_not_help {
            get {
                return ResourceManager.GetString("did_not_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to did not help.
        /// </summary>
        public static string did_not_help_command {
            get {
                return ResourceManager.GetString("did_not_help_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to divide.
        /// </summary>
        public static string divide {
            get {
                return ResourceManager.GetString("divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to divide by.
        /// </summary>
        public static string divide_by {
            get {
                return ResourceManager.GetString("divide_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete {0}?.
        /// </summary>
        public static string do_you_want_to_delete {
            get {
                return ResourceManager.GetString("do_you_want_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does god exist.
        /// </summary>
        public static string does_god_exist {
            get {
                return ResourceManager.GetString("does_god_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurt Nørmark is one of many gods..
        /// </summary>
        public static string does_god_exist_response {
            get {
                return ResourceManager.GetString("does_god_exist_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing setup. Please wait....
        /// </summary>
        public static string doing_setup_please_wait {
            get {
                return ResourceManager.GetString("doing_setup_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string down {
            get {
                return ResourceManager.GetString("down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string examples {
            get {
                return ResourceManager.GetString("examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world..
        /// </summary>
        public static string hello_response {
            get {
                return ResourceManager.GetString("hello_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help:
        ///
        ///Formulating a question:
        ///1. Your question needs to consist of a wh-question word, such as what, for the chatbot to understand what to search for.
        ///2. You can ask “What topics do you know?” to get a list of all the topics available.
        ///
        ///How to use the calculator:
        ///1. Ask the chatbot what numbers you want to add(+), substract(-), divide(/) or multiply(*) with each other for example “What is 5 * 5 / 5”.
        ///2. The mathbot will use the result of the previous calculation unless you write “clear result”..
        /// </summary>
        public static string help_message {
            get {
                return ResourceManager.GetString("help_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help request has been sent to your teacher..
        /// </summary>
        public static string help_request_has_been_sent_to_your_teacher {
            get {
                return ResourceManager.GetString("help_request_has_been_sent_to_your_teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Requests.
        /// </summary>
        public static string help_requests {
            get {
                return ResourceManager.GetString("help_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help requests reset.
        /// </summary>
        public static string help_requests_reset {
            get {
                return ResourceManager.GetString("help_requests_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cannot process more than one sentence at a time..
        /// </summary>
        public static string i_cannot_process_more_than_one_sentence {
            get {
                return ResourceManager.GetString("i_cannot_process_more_than_one_sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I did not understand that sentence. Write “help” for more information..
        /// </summary>
        public static string i_did_not_understand_that_sentence {
            get {
                return ResourceManager.GetString("i_did_not_understand_that_sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not know anything about {0}. These are the topics that I know about:
        ///
        ///{1}.
        /// </summary>
        public static string i_do_not_know_anything_about_that_noun {
            get {
                return ResourceManager.GetString("i_do_not_know_anything_about_that_noun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not have any knowledge about those things. These are the topics that I currently know about:
        ///
        ///{0}.
        /// </summary>
        public static string i_do_not_know_anything_about_those_nouns {
            get {
                return ResourceManager.GetString("i_do_not_know_anything_about_those_nouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_classes {
            get {
                object obj = ResourceManager.GetObject("icon_classes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_log_out {
            get {
                object obj = ResourceManager.GetObject("icon_log_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_materials {
            get {
                object obj = ResourceManager.GetObject("icon_materials", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_users {
            get {
                object obj = ResourceManager.GetObject("icon_users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert image....
        /// </summary>
        public static string insert_image {
            get {
                return ResourceManager.GetString("insert_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It cannot be deleted because it is used in other tables.
        /// </summary>
        public static string it_cannot_be_deleted_because_it_is_used_in_other_tables {
            get {
                return ResourceManager.GetString("it_cannot_be_deleted_because_it_is_used_in_other_tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} removed.
        /// </summary>
        public static string item_removed {
            get {
                return ResourceManager.GetString("item_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string log_out {
            get {
                return ResourceManager.GetString("log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in. Please wait....
        /// </summary>
        public static string logging_in_please_wait {
            get {
                return ResourceManager.GetString("logging_in_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string materials {
            get {
                return ResourceManager.GetString("materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon mathchatbot {
            get {
                object obj = ResourceManager.GetObject("mathchatbot", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mathchatbot_logo {
            get {
                object obj = ResourceManager.GetObject("mathchatbot_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mathchatbot_logo_white {
            get {
                object obj = ResourceManager.GetObject("mathchatbot_logo_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minus.
        /// </summary>
        public static string minus {
            get {
                return ResourceManager.GetString("minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modulus.
        /// </summary>
        public static string modulus {
            get {
                return ResourceManager.GetString("modulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiply.
        /// </summary>
        public static string multiply {
            get {
                return ResourceManager.GetString("multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiply by.
        /// </summary>
        public static string multiply_by {
            get {
                return ResourceManager.GetString("multiply_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help?.
        /// </summary>
        public static string need_help {
            get {
                return ResourceManager.GetString("need_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help.
        /// </summary>
        public static string need_help_command {
            get {
                return ResourceManager.GetString("need_help_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - New Assignment.
        /// </summary>
        public static string new_assignment {
            get {
                return ResourceManager.GetString("new_assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Class.
        /// </summary>
        public static string new_class {
            get {
                return ResourceManager.GetString("new_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New image.
        /// </summary>
        public static string new_image {
            get {
                return ResourceManager.GetString("new_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password again.
        /// </summary>
        public static string new_password_again {
            get {
                return ResourceManager.GetString("new_password_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New term.
        /// </summary>
        public static string new_term {
            get {
                return ResourceManager.GetString("new_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - New Term Definition.
        /// </summary>
        public static string new_term_definition {
            get {
                return ResourceManager.GetString("new_term_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - New Term Definition Example.
        /// </summary>
        public static string new_term_definition_example {
            get {
                return ResourceManager.GetString("new_term_definition_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New topic.
        /// </summary>
        public static string new_topic {
            get {
                return ResourceManager.GetString("new_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - New Topic Definition.
        /// </summary>
        public static string new_topic_definition {
            get {
                return ResourceManager.GetString("new_topic_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        public static string new_user {
            get {
                return ResourceManager.GetString("new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No help requests for this term.
        /// </summary>
        public static string no_help_requests_for_this_term {
            get {
                return ResourceManager.GetString("no_help_requests_for_this_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of help requests.
        /// </summary>
        public static string number_of_help_requests {
            get {
                return ResourceManager.GetString("number_of_help_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old image.
        /// </summary>
        public static string old_image {
            get {
                return ResourceManager.GetString("old_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string overwrite {
            get {
                return ResourceManager.GetString("overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Overwrite Assignment.
        /// </summary>
        public static string overwrite_assignment {
            get {
                return ResourceManager.GetString("overwrite_assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Overwrite Term Definition.
        /// </summary>
        public static string overwrite_term_definition {
            get {
                return ResourceManager.GetString("overwrite_term_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Overwrite Term Definition Example.
        /// </summary>
        public static string overwrite_term_definition_example {
            get {
                return ResourceManager.GetString("overwrite_term_definition_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Overwrite Topic Definition.
        /// </summary>
        public static string overwrite_topic_definition {
            get {
                return ResourceManager.GetString("overwrite_topic_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter proper math function..
        /// </summary>
        public static string please_enter_proper_math_function {
            get {
                return ResourceManager.GetString("please_enter_proper_math_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid input in functions..
        /// </summary>
        public static string please_enter_valid_input_in_functions {
            get {
                return ResourceManager.GetString("please_enter_valid_input_in_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out all fields.
        /// </summary>
        public static string please_fill_out_all_fields {
            get {
                return ResourceManager.GetString("please_fill_out_all_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please perform a correct and legal math operation..
        /// </summary>
        public static string please_perform_a_correct_and_legal_math_operation {
            get {
                return ResourceManager.GetString("please_perform_a_correct_and_legal_math_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a term first before using this command..
        /// </summary>
        public static string please_select_a_term_first_before_using_this_command {
            get {
                return ResourceManager.GetString("please_select_a_term_first_before_using_this_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a term or an example first before using this command..
        /// </summary>
        public static string please_select_a_term_or_example_first_before_using_this_command {
            get {
                return ResourceManager.GetString("please_select_a_term_or_example_first_before_using_this_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a topic first before using this command..
        /// </summary>
        public static string please_select_a_topic_first_before_using_this_command {
            get {
                return ResourceManager.GetString("please_select_a_topic_first_before_using_this_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a topic, a term or an example before using this command..
        /// </summary>
        public static string please_select_a_topic_term_or_example_before_using_this_command {
            get {
                return ResourceManager.GetString("please_select_a_topic_term_or_example_before_using_this_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an assignment first before using this command..
        /// </summary>
        public static string please_select_an_assignment_first_before_using_this_command {
            get {
                return ResourceManager.GetString("please_select_an_assignment_first_before_using_this_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an example first before using this command..
        /// </summary>
        public static string please_select_an_example_first_before_using_this_command {
            get {
                return ResourceManager.GetString("please_select_an_example_first_before_using_this_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image.
        /// </summary>
        public static string please_select_an_image {
            get {
                return ResourceManager.GetString("please_select_an_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one of these topics first:
        ///
        ///{0}.
        /// </summary>
        public static string please_select_one_of_these_topics_first {
            get {
                return ResourceManager.GetString("please_select_one_of_these_topics_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a proper list representation of nouns..
        /// </summary>
        public static string please_write_a_proper_list_representation_of_nouns {
            get {
                return ResourceManager.GetString("please_write_a_proper_list_representation_of_nouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a proper sentence. .
        /// </summary>
        public static string please_write_a_proper_sentence {
            get {
                return ResourceManager.GetString("please_write_a_proper_sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plus.
        /// </summary>
        public static string plus {
            get {
                return ResourceManager.GetString("plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing MathChatBot.
        ///Please wait....
        /// </summary>
        public static string preparing_mathchatbot {
            get {
                return ResourceManager.GetString("preparing_mathchatbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove assignment?.
        /// </summary>
        public static string remove_assignment {
            get {
                return ResourceManager.GetString("remove_assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove definition?.
        /// </summary>
        public static string remove_definition {
            get {
                return ResourceManager.GetString("remove_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove example?.
        /// </summary>
        public static string remove_example {
            get {
                return ResourceManager.GetString("remove_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user from class.
        /// </summary>
        public static string remove_user_from_class {
            get {
                return ResourceManager.GetString("remove_user_from_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string reset_password {
            get {
                return ResourceManager.GetString("reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset requests.
        /// </summary>
        public static string reset_requests {
            get {
                return ResourceManager.GetString("reset_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving data. Please wait....
        /// </summary>
        public static string retrieving_data_please_wait {
            get {
                return ResourceManager.GetString("retrieving_data_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save credentials.
        /// </summary>
        public static string save_credentials {
            get {
                return ResourceManager.GetString("save_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for class....
        /// </summary>
        public static string search_for_class {
            get {
                return ResourceManager.GetString("search_for_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for user....
        /// </summary>
        public static string search_for_user {
            get {
                return ResourceManager.GetString("search_for_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See.
        /// </summary>
        public static string see {
            get {
                return ResourceManager.GetString("see", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See answers.
        /// </summary>
        public static string see_answers {
            get {
                return ResourceManager.GetString("see_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See assignments.
        /// </summary>
        public static string see_assignments {
            get {
                return ResourceManager.GetString("see_assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See definition.
        /// </summary>
        public static string see_definition {
            get {
                return ResourceManager.GetString("see_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See example.
        /// </summary>
        public static string see_example {
            get {
                return ResourceManager.GetString("see_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See examples.
        /// </summary>
        public static string see_examples {
            get {
                return ResourceManager.GetString("see_examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See for whole class.
        /// </summary>
        public static string see_for_whole_class {
            get {
                return ResourceManager.GetString("see_for_whole_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Image.
        /// </summary>
        public static string see_image {
            get {
                return ResourceManager.GetString("see_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See requests.
        /// </summary>
        public static string see_requests {
            get {
                return ResourceManager.GetString("see_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See roles.
        /// </summary>
        public static string see_roles {
            get {
                return ResourceManager.GetString("see_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See term.
        /// </summary>
        public static string see_term {
            get {
                return ResourceManager.GetString("see_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See terms.
        /// </summary>
        public static string see_terms {
            get {
                return ResourceManager.GetString("see_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See users.
        /// </summary>
        public static string see_users {
            get {
                return ResourceManager.GetString("see_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select assignment.
        /// </summary>
        public static string select_assignment {
            get {
                return ResourceManager.GetString("select_assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image.
        /// </summary>
        public static string select_image {
            get {
                return ResourceManager.GetString("select_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select material.
        /// </summary>
        public static string select_material {
            get {
                return ResourceManager.GetString("select_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show order ID.
        /// </summary>
        public static string show_order_id {
            get {
                return ResourceManager.GetString("show_order_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when saving changes to the database..
        /// </summary>
        public static string something_went_wrong_when_saving_changes_to_the_database {
            get {
                return ResourceManager.GetString("something_went_wrong_when_saving_changes_to_the_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source requests.
        /// </summary>
        public static string source_requests {
            get {
                return ResourceManager.GetString("source_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source type.
        /// </summary>
        public static string source_type {
            get {
                return ResourceManager.GetString("source_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substract.
        /// </summary>
        public static string substract {
            get {
                return ResourceManager.GetString("substract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully gone through file.
        /// </summary>
        public static string successfully_gone_through_file {
            get {
                return ResourceManager.GetString("successfully_gone_through_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me a joke.
        /// </summary>
        public static string tell_me_a_joke {
            get {
                return ResourceManager.GetString("tell_me_a_joke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you heard the one about the statistician? Probably..
        /// </summary>
        public static string tell_me_a_joke_response {
            get {
                return ResourceManager.GetString("tell_me_a_joke_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        public static string term {
            get {
                return ResourceManager.GetString("term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Term Definition Examples.
        /// </summary>
        public static string term_defition_examples {
            get {
                return ResourceManager.GetString("term_defition_examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Help Request Sources.
        /// </summary>
        public static string term_help_request_sources {
            get {
                return ResourceManager.GetString("term_help_request_sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term name.
        /// </summary>
        public static string term_name {
            get {
                return ResourceManager.GetString("term_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string terms {
            get {
                return ResourceManager.GetString("terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class already exists.
        /// </summary>
        public static string the_class_already_exists {
            get {
                return ResourceManager.GetString("the_class_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password needs to be at least 8 characters long..
        /// </summary>
        public static string the_password_has_to_be_at_least_eight_characters_long {
            get {
                return ResourceManager.GetString("the_password_has_to_be_at_least_eight_characters_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords need to match..
        /// </summary>
        public static string the_passwords_need_to_match {
            get {
                return ResourceManager.GetString("the_passwords_need_to_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} assignment(s) for this term. This is the first one..
        /// </summary>
        public static string there_are_for_this_term_this_is_the_first_assignment {
            get {
                return ResourceManager.GetString("there_are_for_this_term_this_is_the_first_assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no assignments for this..
        /// </summary>
        public static string there_are_no_assignments_for_this {
            get {
                return ResourceManager.GetString("there_are_no_assignments_for_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no more assignments..
        /// </summary>
        public static string there_are_no_more_assignments {
            get {
                return ResourceManager.GetString("there_are_no_more_assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no previous assignments..
        /// </summary>
        public static string there_are_no_previous_assignments {
            get {
                return ResourceManager.GetString("there_are_no_previous_assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} assignment(s) under this topic. This is the first one..
        /// </summary>
        public static string there_are_under_this_topic_this_is_the_first_assignment {
            get {
                return ResourceManager.GetString("there_are_under_this_topic_this_is_the_first_assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are terms under {0}:
        ///
        ///{1}.
        /// </summary>
        public static string these_are_the_terms_under {
            get {
                return ResourceManager.GetString("these_are_the_terms_under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the topics that I know about:
        ///
        ///{0}.
        /// </summary>
        public static string these_are_the_topics_i_know_about {
            get {
                return ResourceManager.GetString("these_are_the_topics_i_know_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This assignment has no answers..
        /// </summary>
        public static string this_assignment_has_no_answers {
            get {
                return ResourceManager.GetString("this_assignment_has_no_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the answer(s) for the assignment:
        ///
        ///{0}.
        /// </summary>
        public static string this_is_the_answers_for_the_assignment {
            get {
                return ResourceManager.GetString("this_is_the_answers_for_the_assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the example(s) I found for {0}..
        /// </summary>
        public static string this_is_the_examples_i_found_for {
            get {
                return ResourceManager.GetString("this_is_the_examples_i_found_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the definition(s) I found for {0}..
        /// </summary>
        public static string this_is_what_i_found_about {
            get {
                return ResourceManager.GetString("this_is_what_i_found_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This term has no examples..
        /// </summary>
        public static string this_term_has_no_examples {
            get {
                return ResourceManager.GetString("this_term_has_no_examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        public static string times {
            get {
                return ResourceManager.GetString("times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string topic {
            get {
                return ResourceManager.GetString("topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Topic Definitions.
        /// </summary>
        public static string topic_definitions {
            get {
                return ResourceManager.GetString("topic_definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic name.
        /// </summary>
        public static string topic_name {
            get {
                return ResourceManager.GetString("topic_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        public static string topics {
            get {
                return ResourceManager.GetString("topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string up {
            get {
                return ResourceManager.GetString("up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string user_information {
            get {
                return ResourceManager.GetString("user_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is deactivated. Contact your administrator to get more info..
        /// </summary>
        public static string user_is_deactivated_contact_your_administrator {
            get {
                return ResourceManager.GetString("user_is_deactivated_contact_your_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to MathChatBot.
        ///Ask me anything math-related and I might be able to help you.
        ///Write “help” to get more information..
        /// </summary>
        public static string welcome_to_mathchatbot {
            get {
                return ResourceManager.GetString("welcome_to_mathchatbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the meaning of life.
        /// </summary>
        public static string what_is_the_meaning_of_life {
            get {
                return ResourceManager.GetString("what_is_the_meaning_of_life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.
        /// </summary>
        public static string what_is_the_meaning_of_life_response {
            get {
                return ResourceManager.GetString("what_is_the_meaning_of_life_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your name.
        /// </summary>
        public static string what_is_your_name {
            get {
                return ResourceManager.GetString("what_is_your_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My name is Kurt..
        /// </summary>
        public static string what_is_your_name_response {
            get {
                return ResourceManager.GetString("what_is_your_name_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you searched for is both a topic and a term which one do you want?.
        /// </summary>
        public static string what_you_searched_for_is_both_a_topic_and_a_term_which_one_do_you_want {
            get {
                return ResourceManager.GetString("what_you_searched_for_is_both_a_topic_and_a_term_which_one_do_you_want", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is your creator.
        /// </summary>
        public static string who_is_your_creator {
            get {
                return ResourceManager.GetString("who_is_your_creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My creators are a group of people from Aalborg University..
        /// </summary>
        public static string who_is_your_creator_response {
            get {
                return ResourceManager.GetString("who_is_your_creator_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password.
        /// </summary>
        public static string wrong_username_or_password {
            get {
                return ResourceManager.GetString("wrong_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only use this command when having a selection..
        /// </summary>
        public static string you_can_only_use_this_command_when_having_a_selection {
            get {
                return ResourceManager.GetString("you_can_only_use_this_command_when_having_a_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot divide by zero..
        /// </summary>
        public static string you_cannot_divide_by_zero {
            get {
                return ResourceManager.GetString("you_cannot_divide_by_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot take square root of a negative number..
        /// </summary>
        public static string you_cannot_take_square_root_of_negative_number {
            get {
                return ResourceManager.GetString("you_cannot_take_square_root_of_negative_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already sent a help request for this..
        /// </summary>
        public static string you_have_already_sent_a_help_request_for_this_material {
            get {
                return ResourceManager.GetString("you_have_already_sent_a_help_request_for_this_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not started any assignments yet..
        /// </summary>
        public static string you_have_not_started_any_assignments_yet {
            get {
                return ResourceManager.GetString("you_have_not_started_any_assignments_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be a student to make help requests..
        /// </summary>
        public static string you_need_to_be_a_student_to_make_help_requests {
            get {
                return ResourceManager.GetString("you_need_to_be_a_student_to_make_help_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total value has been set to 0..
        /// </summary>
        public static string your_total_value_has_been_set_to_0 {
            get {
                return ResourceManager.GetString("your_total_value_has_been_set_to_0", resourceCulture);
            }
        }
    }
}
