//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathChatBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathChatBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        public static string activated {
            get {
                return ResourceManager.GetString("activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add users from file.
        /// </summary>
        public static string add_users_from_file {
            get {
                return ResourceManager.GetString("add_users_from_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding users from file. Please wait....
        /// </summary>
        public static string adding_users_from_file_please_wait {
            get {
                return ResourceManager.GetString("adding_users_from_file_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Controls.
        /// </summary>
        public static string admin_controls_title {
            get {
                return ResourceManager.GetString("admin_controls_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - MathChatBot.
        /// </summary>
        public static string application_title {
            get {
                return ResourceManager.GetString("application_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string classes {
            get {
                return ResourceManager.GetString("classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the following problems has occured:\n\n1. You have given a name that is not at least 2 letters long.\n2. You have given a password that is not at least 8 characters long..
        /// </summary>
        public static string create_user_error {
            get {
                return ResourceManager.GetString("create_user_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_classes {
            get {
                object obj = ResourceManager.GetObject("icon_classes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_users {
            get {
                object obj = ResourceManager.GetObject("icon_users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon mathchatbot {
            get {
                object obj = ResourceManager.GetObject("mathchatbot", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mathchatbot_logo {
            get {
                object obj = ResourceManager.GetObject("mathchatbot_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mathchatbot_logo_white {
            get {
                object obj = ResourceManager.GetObject("mathchatbot_logo_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New class.
        /// </summary>
        public static string new_class {
            get {
                return ResourceManager.GetString("new_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password again.
        /// </summary>
        public static string new_password_again {
            get {
                return ResourceManager.GetString("new_password_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        public static string new_user {
            get {
                return ResourceManager.GetString("new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string reset_password {
            get {
                return ResourceManager.GetString("reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save credentials.
        /// </summary>
        public static string save_credentials {
            get {
                return ResourceManager.GetString("save_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for class....
        /// </summary>
        public static string search_for_class {
            get {
                return ResourceManager.GetString("search_for_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for user....
        /// </summary>
        public static string search_for_user {
            get {
                return ResourceManager.GetString("search_for_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See roles.
        /// </summary>
        public static string see_roles {
            get {
                return ResourceManager.GetString("see_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See users.
        /// </summary>
        public static string see_users {
            get {
                return ResourceManager.GetString("see_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went when saving changes to the database.
        /// </summary>
        public static string something_went_wrong_when_saving_changes_to_the_database {
            get {
                return ResourceManager.GetString("something_went_wrong_when_saving_changes_to_the_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully gone through file.
        /// </summary>
        public static string successfully_gone_through_file {
            get {
                return ResourceManager.GetString("successfully_gone_through_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password needs to be at least 8 characters long.
        /// </summary>
        public static string the_password_has_to_be_at_least_eight_characters_long {
            get {
                return ResourceManager.GetString("the_password_has_to_be_at_least_eight_characters_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords need to match.
        /// </summary>
        public static string the_passwords_need_to_match {
            get {
                return ResourceManager.GetString("the_passwords_need_to_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string user_information {
            get {
                return ResourceManager.GetString("user_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
    }
}
